<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PhDProgram; // Ensure the PhDProgram model is imported

class PhDProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data transcribed from database/UTM FC PhD Programs.csv
        $programs = [
            [
                'name' => 'Doctor of Philosophy - Field: Computer Science',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'This programme allows students to conduct an independent research in an area of computer science, under the supervision of a member staff with related expertise',
                'duration_years' => '3 until 8',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/doctor-of-philosophy-cs/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Doctor of Philosophy - Field: Software Engineering',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'The programme is offered on full-time basis and is based on a 2-Semester per academic session. This is a full research programme. The candidate is supervised by a lecturer.',
                'duration_years' => '3 until 8',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/doctor-of-philosophy-se/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Doctor of Philosophy - Field: Informatics Engineeering',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'The programme is offered on full-time basis and is based on 2-Semester per academic session. This ia a full research programme.',
                'duration_years' => '3 until 8',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/doctor-of-philosophy-ci/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Philosophy - Field: Software Engineering',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'In this programme is a full guided research Master programme designed for candidates who wish to obtain knowledge, skills and expertise in software engineering theories and able to apply them to produce high quality software and to propose new or improved software engineering techniques methods and tools.',
                'duration_years' => '2 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-of-philosophy-se/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Philosophy - Field: Computer Science',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'These programmes allow students to conduct an independent research in an area of Computer Science, under the supervision of a members of staff with related expertise Assessment is by semester progress reports and a thesis examination (viva voce)',
                'duration_years' => '2 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-of-philosophy-cs/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Computer Science',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'This program is offered on full-time basis and is based on a 2-semester per academic session. This is a mixed-mode',
                'duration_years' => '1 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-cs/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master in Data Science',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'In this programme, MSc (Data Science), you will gain a solid understanding of the methods used in data science.',
                'duration_years' => '1 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-of-science-ds/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master in Innovative Computing',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'The program is a general program for computing field that provides exposure in computing science, science and technology engineering, mathematics and social sciences.',
                'duration_years' => '1 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-ic/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Cyber Security',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'This program is designed to produce ethical cybersecurity experts with cutting-edge skills and knowledge to protect organizations from evolving cyber threats. Benefit from industry-leading lecturers, hands-on learning experiences, and wide networking opportunities. Secure your place in one of the fastest-growing fields and become a leader in safeguarding the digital world.',
                'duration_years' => '1 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-csy/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Science (Informatics)',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'This program emphasizes the application and critical understanding of emerging technologies to address real-world challenges for digital transformation.',
                'duration_years' => '1 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-of-science-informatics/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master in Software Engineering',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => "A Master's program designed to equip future software engineers with advanced technical skills, leadership qualities, and ethical values to drive impactful software solutions.",
                'duration_years' => '1 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://comp.utm.my/master-in-software-engineering/',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Doctor of Professional Practice (DPP)',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'The Doctor of Professional Practice program, the first of its kind in Malaysia by UTM, combines coursework and research, allowing professionals to apply their experience to doctoral-level research. ',
                'duration_years' => '3 until 8',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://odl.utm.my/doctor-of-professional-practice-dpp/?_gl=1*10ltz11*_ga*MTAxMDQzNTA2MC4xNzU0ODM3MDQ3*_ga_N3HJW8G3P7*czE3NTQ4MzcwNDckbzEkZzEkdDE3NTQ4Mzk2MDckajE4JGwwJGgw',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ODL Master of Cyber Security',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'This programme is designed to meet the needs for flexibility and convenience through fully online teaching and learning Open Distance Learning (ODL) enables study from anywhere anytime while accesing top-tier education.',
                'duration_years' => '1.5 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://odl.utm.my/master-of-cyber-security/?_gl=1*10ltz11*_ga*MTAxMDQzNTA2MC4xNzU0ODM3MDQ3*_ga_N3HJW8G3P7*czE3NTQ4MzcwNDckbzEkZzEkdDE3NTQ4Mzk2MDckajE4JGwwJGgw',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ODL Master of Computer Science',
                'university_id' => 5,
                'faculty_id' => 60,
                'description' => 'The Master of Computer Science is offered on a full-time basis (open Distance Learning). The Open Distance Learning (ODL) study is conducted fully online.',
                'duration_years' => '1.5 until 4',
                'funding_info' => 'Self-funded or external scholarships',
                'application_url' => 'https://odl.utm.my/master-of-computer-science/?_gl=1*10ltz11*_ga*MTAxMDQzNTA2MC4xNzU0ODM3MDQ3*_ga_N3HJW8G3P7*czE3NTQ4MzcwNDckbzEkZzEkdDE3NTQ4Mzk2MDckajE4JGwwJGgw',
                'country' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Use the insert method for a single, efficient database query
        PhDProgram::insert($programs);
    }
}

