import React from 'react';
import { Brain, Search, FileText, Sparkles, Target, Lightbulb } from 'lucide-react';
import { Link } from '@inertiajs/react';

const DecodingMatchInsights = () => {
    return (
        <div className="space-y-8">
            <div className="border-b border-gray-200 pb-6">
                <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 leading-tight">
                    Decoding Your AI Match Insights: A Look at Our GPT-4o Powered Recommendations
                </h1>
                <p className="text-base sm:text-lg text-gray-600 leading-relaxed">
                    You've just searched for a supervisor or a postgraduate program on Nexscholar, and alongside the list of results, you see a small, highlighted box with a summary explaining why a specific person or program is a good fit. What is this, and how does it work?
                </p>
                <p className="text-gray-700 mt-4">
                    That's your AI Match Insight, a feature designed to act as your personal research assistant. It cuts through the noise, saving you hours of manual comparison by providing a clear, concise recommendation at a glance.
                </p>
                <p className="text-gray-700 mt-2">
                    Here in Johor Bahru, we're building tools to make academic life more efficient. In this article, we'll pull back the curtain and show you exactly how our advanced AI, powered by OpenAI's world-class GPT-4o model, crafts these personalized insights just for you.
                </p>
            </div>

            <div className="grid gap-4 sm:gap-6 lg:gap-8">
                {/* What is an AI Match Insight */}
                <section className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-4 sm:p-6 lg:p-8">
                    <div className="flex items-center gap-3 mb-6">
                        <Brain className="w-6 h-6 text-blue-600" />
                        <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 leading-tight">What is an AI Match Insight?</h2>
                    </div>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        Think of an AI Match Insight as more than just a summary; it's the beginning of a story. It's a short, personalized analysis generated by our AI that highlights the strongest points of connection between you and a potential supervisor, collaborator, or postgraduate program.
                    </p>
                    <div className="bg-blue-100 rounded-lg p-4">
                        <p className="text-blue-800 text-sm">
                            <strong>💡 Key Insight:</strong> It goes beyond just matching keywords. It analyzes context, understands nuance, and identifies potential synergies that you might have missed, giving you a powerful starting point for your own research.
                        </p>
                    </div>
                </section>

                {/* Hero Image Placeholder */}
                <div className="bg-gray-100 rounded-lg p-4 sm:p-6 lg:p-8 text-center">
                    <img
                        src="/images/resources/2.1.1.jpg"
                        className="w-full max-w-2xl mx-auto rounded-lg shadow-lg"
                    />
                </div>

                {/* The Ingredients */}
                <section>
                    <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-4 sm:mb-6 flex items-center gap-3 leading-tight">
                        <FileText className="w-5 h-5 sm:w-6 sm:h-6 text-green-600" />
                        The "Ingredients" of Your Personalized Insight
                    </h2>
                    <p className="text-gray-700 leading-relaxed mb-8">
                        Transparency is key to trust. To craft a relevant insight, our AI acts like a chef, combining several key "ingredients" from both you and the potential match.
                    </p>

                    <div className="space-y-6">
                        {/* Supervisor & Collaborator Matches */}
                        <div className="bg-white border border-gray-200 rounded-lg p-6">
                            <h3 className="text-xl font-semibold text-gray-900 mb-4 flex items-center gap-2">
                                <Target className="w-5 h-5 text-blue-600" />
                                For Supervisor & Collaborator Matches, the AI analyzes:
                            </h3>
                            <div className="grid md:grid-cols-1 lg:grid-cols-3 gap-4">
                                <div className="bg-blue-50 rounded-lg p-4">
                                    <h4 className="font-semibold text-blue-900 mb-2">Your Academic DNA</h4>
                                    <p className="text-blue-800 text-sm">
                                        It starts with your profile—your structured research fields, your descriptive bio, and your specific search query.
                                    </p>
                                </div>
                                <div className="bg-green-50 rounded-lg p-4">
                                    <h4 className="font-semibold text-green-900 mb-2">The Academic's Profile</h4>
                                    <p className="text-green-800 text-sm">
                                        It then examines the potential match's profile, including their position, department, and listed research expertise.
                                    </p>
                                </div>
                                <div className="bg-purple-50 rounded-lg p-4">
                                    <h4 className="font-semibold text-purple-900 mb-2">Their Body of Work</h4>
                                    <p className="text-purple-800 text-sm">
                                        Here's the most powerful part: the AI also considers their publication history from their synced Google Scholar profile. It looks at the titles and topics of their recent papers to find direct, tangible overlaps with your interests.
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Postgraduate Program Recommendations */}
                        <div className="bg-white border border-gray-200 rounded-lg p-6">
                            <h3 className="text-xl font-semibold text-gray-900 mb-4 flex items-center gap-2">
                                <Search className="w-5 h-5 text-orange-600" />
                                For Postgraduate Program Recommendations, the AI analyzes:
                            </h3>
                            <div className="grid md:grid-cols-2 gap-4">
                                <div className="bg-orange-50 rounded-lg p-4">
                                    <h4 className="font-semibold text-orange-900 mb-2">Your Background & Goals</h4>
                                    <p className="text-orange-800 text-sm">
                                        It processes the content from your uploaded CV and your stated research interests.
                                    </p>
                                </div>
                                <div className="bg-red-50 rounded-lg p-4">
                                    <h4 className="font-semibold text-red-900 mb-2">The Program's Core Focus</h4>
                                    <p className="text-red-800 text-sm">
                                        It analyzes the program's official description, curriculum, funding information, and the expertise of its faculty members to find the perfect alignment.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* How It Works */}
                <section className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg p-4 sm:p-6 lg:p-8">
                    <div className="flex items-center gap-3 mb-6">
                        <Sparkles className="w-6 h-6 text-purple-600" />
                        <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 leading-tight">How It Works: A Simple 3-Step Process</h2>
                    </div>
                    <p className="text-gray-700 leading-relaxed mb-8">
                        While the technology is complex, the process is straightforward.
                    </p>

                    {/* Process Image Placeholder */}
                    <div className="bg-gray-100 rounded-lg p-4 sm:p-6 lg:p-8 text-center mb-4 sm:mb-6 lg:mb-8">
                        <img
                            src="/images/resources/2.1.2.png"
                            alt="AI Matching Process Diagram"
                            className="w-full max-w-2xl mx-auto rounded-lg shadow-lg"
                        />
                    </div>

                    <div className="space-y-6">
                        {/* Step 1 */}
                        <div className="bg-white rounded-lg p-6 shadow-sm">
                            <div className="flex items-start gap-4">
                                <div className="flex-shrink-0 w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
                                    <span className="text-blue-800 font-bold text-lg">1</span>
                                </div>
                                <div className="flex-1">
                                    <h3 className="text-xl font-semibold text-gray-900 mb-3">Contextual Analysis</h3>
                                    <p className="text-gray-700 leading-relaxed">
                                        First, our system gathers all the relevant "ingredients" listed above into a single, comprehensive context. It looks at your profile, the potential match's profile, their publications, and your search query all at once.
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Step 2 */}
                        <div className="bg-white rounded-lg p-6 shadow-sm">
                            <div className="flex items-start gap-4">
                                <div className="flex-shrink-0 w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                                    <span className="text-green-800 font-bold text-lg">2</span>
                                </div>
                                <div className="flex-1">
                                    <h3 className="text-xl font-semibold text-gray-900 mb-3">Synthesis by GPT-4o</h3>
                                    <p className="text-gray-700 leading-relaxed">
                                        Next, we feed this rich context to OpenAI's powerful GPT-4o model. We give it a specific instruction: "Act as an experienced academic advisor and identify the strongest, most relevant points of connection between these two profiles."
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Step 3 */}
                        <div className="bg-white rounded-lg p-6 shadow-sm">
                            <div className="flex items-start gap-4">
                                <div className="flex-shrink-0 w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center">
                                    <span className="text-purple-800 font-bold text-lg">3</span>
                                </div>
                                <div className="flex-1">
                                    <h3 className="text-xl font-semibold text-gray-900 mb-3">A Clear, Concise Recommendation</h3>
                                    <p className="text-gray-700 leading-relaxed">
                                        Finally, the AI drafts the clear, bullet-pointed insight you see on your results page. It highlights the most compelling reasons for the match, giving you a data-driven reason to explore the opportunity further.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* How to Get the Best Insights */}
                <section>
                    <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-4 sm:mb-6 flex items-center gap-3 leading-tight">
                        <Lightbulb className="w-5 h-5 sm:w-6 sm:h-6 text-amber-600" />
                        How to Get the Best and Most Accurate Insights
                    </h2>
                    <p className="text-gray-700 leading-relaxed mb-8">
                        The lesson is simple: The quality of your insights depends directly on the quality of your profile.
                    </p>
                    <div className="bg-amber-50 border border-amber-200 rounded-lg p-6">
                        <p className="text-amber-800 mb-4">
                            <strong>💡 Pro Tip:</strong> A detailed and up-to-date profile is the best "ingredient" you can give our AI. To ensure you're getting the most accurate recommendations possible:
                        </p>
                        <ul className="space-y-3 text-amber-800">
                            <li className="flex items-start gap-2">
                                <span className="text-amber-600 font-bold">•</span>
                                <div>
                                    <strong>Complete Your Profile:</strong> Use our{' '}
                                    <Link
                                        href={route('resources.guide', ['mastering-profile', 'profile-health-checklist'])}
                                        className="text-amber-900 underline hover:text-amber-700 font-semibold"
                                    >
                                        Profile Health Checklist
                                    </Link>{' '}
                                    to make sure you've filled out all the key sections.
                                </div>
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-amber-600 font-bold">•</span>
                                <div>
                                    <strong>Optimize Your CV:</strong> A well-structured CV gives our AI the clearest information. Follow the tips in our{' '}
                                    <Link
                                        href={route('resources.guide', ['mastering-profile', 'crafting-academic-cv'])}
                                        className="text-amber-900 underline hover:text-amber-700 font-semibold"
                                    >
                                        CV Crafting Guide
                                    </Link>
                                    .
                                </div>
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="text-amber-600 font-bold">•</span>
                                <div>
                                    <strong>Be Specific:</strong> The more specific you are in your bio and structured research fields, the more material our AI has to work with to find those hidden-gem connections.
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>

                {/* Call to Action */}
                <section className="bg-gradient-to-r from-green-600 to-emerald-600 rounded-lg p-4 sm:p-6 lg:p-8 text-white text-center">
                    <h2 className="text-xl sm:text-2xl font-semibold mb-4 leading-tight">Your Starting Point for Discovery</h2>
                    <p className="text-green-100 mb-6 leading-relaxed">
                        Our AI Match Insight is a powerful tool designed to save you time, surface relevant opportunities, and help you see connections you might have otherwise missed.
                    </p>
                    <p className="text-green-200 mb-6">
                        Trust the process, but always remember to do your own in-depth research. Use our AI insights as your intelligent starting point for a deeper dive. Happy connecting!
                    </p>
                </section>
            </div>
        </div>
    );
};

export default DecodingMatchInsights;
