import { useState } from "react";
import InputLabel from '@/Components/InputLabel';
import Select from 'react-select';
import InputError from '@/Components/InputError';

const nationalities = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "United States",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Barbuda",
    "Botswana",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Brazil",
    "United Kingdom",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Netherlands",
    "East Timor",
    "Ecuador",
    "Egypt",
    "United Arab Emirates",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Philippines",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea-Bissau",
    "Guinea",
    "Guyana",
    "Haiti",
    "Bosnia and Herzegovina",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Saint Kitts and Nevis",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "North Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Morocco",
    "Myanmar",
    "Lesotho",
    "Botswana",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "New Zealand",
    "Vanuatu",
    "Nicaragua",
    "Nigeria",
    "Niger",
    "North Korea",
    "Northern Ireland",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Lucia",
    "El Salvador",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Eswatini",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Wales",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

export default function NationalityForm({ value, onChange, title, isNotSpecify, errors }) {
    // Transform array to options
    let options = nationalities.map(nat => ({ value: nat, label: nat }));
    // If needed, add extra options at the beginning
    if (isNotSpecify) {
        options = [
            { value: "Not Specified", label: "Not Specified" },
            { value: "All Country", label: "All Country" },
            ...options,
        ];
    }
    // Find the selected option based on value
    const selectedOption = options.find(option => option.value === value) || null;

    return (
        <div>
            <InputLabel htmlFor="nationality" className="block font-medium text-gray-700">
                {title} <span className="text-red-600">*</span>
            </InputLabel>
            <Select
                id="nationality"
                options={options}
                value={selectedOption}
                onChange={(option) => onChange(option.value)}
                placeholder={`Select ${title}...`}
                className="mt-1 block w-full border-gray-300 rounded-md shadow-sm"
                classNamePrefix="react-select"
                isSearchable
                required
            />
            <InputError className="mt-2" message={errors[title]} />
        </div>
    );
}
